sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t slipmatsteve/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true slipmatsteve/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: 'docker'
  env: 'docker-env'
  bucket_name: "elasticbeanstalk-us-east-2-047305148897"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
